// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// The ODE Function of Chemical Model File
// 
// Generated by KPP-3.4.0 symbolic chemistry Kinetics PreProcessor
//       (https:/github.com/KineticPreProcessor/KPP)
// KPP is distributed under GPL, the general public licence
//       (http://www.gnu.org/copyleft/gpl.html)
// (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
// (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
//     With important contributions from:
//        M. Damian,   Villanova University, Philadelphia, PA, USA
//        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
//        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
//        H. Lin,      Harvard University, Cambridge, MA, USA
//        R. Yantosca, Harvard University, Cambridge, MA, USA
//        P.O. Sturm,  Univ. of Southern California, Los Angeles, CA, USA
// 
// File                 : small_strato_Function.c
// Equation file        : small_strato.kpp
// Output root filename : .
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "small_strato_Parameters.h"
#include "small_strato_Global.h"
#include "small_strato_Sparse.h"


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Fun - time derivatives of variables - Aggregate form
//   Arguments :
//      V         - Concentrations of variable species (local)
//      F         - Concentrations of fixed species (local)
//      RCT       - Rate constants (local)
//      Vdot      - Time derivative of variable species concentrations
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void Fun( 
  double V[NVAR],                        /* Concentrations of variable species (local) */
  double F[NFIX],                        /* Concentrations of fixed species (local) */
  double RCT[NREACT],                    /* Rate constants (local) */
  double Vdot[NVAR]                      /* Time derivative of variable species concentrations */
)
{

// Local variables
double A[NREACT];                        /* Rate for each equation */

// Computation of equation rates
  A[0] = RCT[0]*F[1];
  A[1] = RCT[1]*V[1]*F[1];
  A[2] = RCT[2]*V[2];
  A[3] = RCT[3]*V[1]*V[2];
  A[4] = RCT[4]*V[2];
  A[5] = RCT[5]*V[0]*F[0];
  A[6] = RCT[6]*V[0]*V[2];
  A[7] = RCT[7]*V[2]*V[3];
  A[8] = RCT[8]*V[1]*V[4];
  A[9] = RCT[9]*V[4];


// Aggregate function
  Vdot[0] = A[4]-A[5]-A[6];
  Vdot[1] = 2*A[0]-A[1]+A[2]-A[3]+A[5]-A[8]+A[9];
  Vdot[2] = A[1]-A[2]-A[3]-A[4]-A[6]-A[7];
  Vdot[3] = -A[7]+A[8]+A[9];
  Vdot[4] = A[7]-A[8]-A[9];
}

// End of Fun function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// Fun_SPLIT - time derivatives of variables - Split form
//   Arguments :
//      V         - Concentrations of variable species (local)
//      F         - Concentrations of fixed species (local)
//      RCT       - Rate constants (local)
//      Vdot      - Time derivative of variable species concentrations
//      P_VAR     - Production term
//      D_VAR     - Destruction term
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void Fun_SPLIT( 
  double V[NVAR],                        /* Concentrations of variable species (local) */
  double F[NFIX],                        /* Concentrations of fixed species (local) */
  double RCT[NREACT],                    /* Rate constants (local) */
  double Vdot[NVAR],                     /* Time derivative of variable species concentrations */
  double P_VAR[NVAR],                    /* Production term */
  double D_VAR[NVAR]                     /* Destruction term */
)
{

// Local variables
double A[NREACT];                        /* Rate for each equation */

// Computation of equation rates
  A[0] = RCT[0]*F[1];
  A[1] = RCT[1]*V[1]*F[1];
  A[2] = RCT[2]*V[2];
  A[4] = RCT[4]*V[2];
  A[5] = RCT[5]*V[0]*F[0];
  A[7] = RCT[7]*V[2]*V[3];
  A[8] = RCT[8]*V[1]*V[4];
  A[9] = RCT[9]*V[4];


// Production function
  P_VAR[0] = A[4];
  P_VAR[1] = 2*A[0]+A[2]+A[5]+A[9];
  P_VAR[2] = A[1];
  P_VAR[3] = A[8]+A[9];
  P_VAR[4] = A[7];

// Destruction function
  D_VAR[0] = RCT[5]*F[0]+RCT[6]*V[2];
  D_VAR[1] = RCT[1]*F[1]+RCT[3]*V[2]+RCT[8]*V[4];
  D_VAR[2] = RCT[2]+RCT[3]*V[1]+RCT[4]+RCT[6]*V[0]+RCT[7]*V[3];
  D_VAR[3] = RCT[7]*V[2];
  D_VAR[4] = RCT[8]*V[1]+RCT[9];

  for( int n=0; n<NVAR; n++ ) {
    Vdot[n] = P_VAR[n] - D_VAR[n]*V[n];
  }
}

// End of Fun_SPLIT function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 
// CalcStoichNum - calculate stoichiometric numbers
//   Arguments :
//      StoichNum - Stoichiometric numbers
// 
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

void CalcStoichNum( 
  double StoichNum[NVAR][NREACT]         /* Stoichiometric numbers */
)
{
  StoichNum[0][4] = 1;
  StoichNum[0][5] = -1;
  StoichNum[0][6] = -1;
  StoichNum[1][0] = 2;
  StoichNum[1][1] = -1;
  StoichNum[1][2] = 1;
  StoichNum[1][3] = -1;
  StoichNum[1][5] = 1;
  StoichNum[1][8] = -1;
  StoichNum[1][9] = 1;
  StoichNum[2][1] = 1;
  StoichNum[2][2] = -1;
  StoichNum[2][3] = -1;
  StoichNum[2][4] = -1;
  StoichNum[2][6] = -1;
  StoichNum[2][7] = -1;
  StoichNum[3][7] = -1;
  StoichNum[3][8] = 1;
  StoichNum[3][9] = 1;
  StoichNum[4][7] = 1;
  StoichNum[4][8] = -1;
  StoichNum[4][9] = -1;
}

// End of CalcStoichNum function
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


