# kpp_small_strato.i — KPP small_strato mechanism validation (box mode)
#
# Validates the KPP Rosenbrock solver integration in box mode.
# Small stratospheric mechanism: 5 species (O1D, O, O3, NO, NO2), 10 reactions.
# The KPP shared library is auto-discovered from the .kpp file path.
#
# Build the .so:
#   make -f modules/atmospheric_chemistry/kpp/build/Makefile \
#     MECH=modules/atmospheric_chemistry/test/tests/actions/kpp_small_strato/small_strato.kpp
#
# Gold CSV generated by: kpp small_test.kpp && make -f Makefile_small_test && ./small_test.exe

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 1
    nx = 1
  []
[]

[AtmosphericChemistry]
  [Box]
    mechanism_file = 'kpp_small_strato/small_strato.kpp'
    temperature = 298.0
    air_density = 2.5e19
    press = 1013.0
    chem_solver = kpp_rosenbrock
  []
[]

[ICs]
  [O1D_ic] type = ScalarConstantIC variable = O1D value = 9.906e1 []
  [O_ic]   type = ScalarConstantIC variable = O    value = 6.624e8 []
  [O3_ic]  type = ScalarConstantIC variable = O3   value = 5.326e11 []
  [NO_ic]  type = ScalarConstantIC variable = NO   value = 8.725e8 []
  [NO2_ic] type = ScalarConstantIC variable = NO2  value = 2.240e8 []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  scheme = 'bdf2'
  end_time = 86400
  dt = 900
  l_max_its = 50
  l_tol = 1e-5
  nl_max_its = 10
  petsc_options_iname = '-pc_type -pc_factor_shift_type'
  petsc_options_value = 'lu NONZERO'
  nl_rel_tol = 1e-10
  nl_abs_tol = 1e-12
  [TimeStepper]
    type = ConstantDT
    dt = 900
  []
[]

[Outputs]
  checkpoint = false
  csv = true
  execute_on = 'timestep_end'
  file_base = 'kpp_small_strato'
  time_step_interval = 10
[]
