# vs analytical B(t) — algorithm-independent accuracy verification
# B(t) = 1/(40*exp(0.01*t)-20) is the exact solution of dB/dt = -K2*B - 2*K4*B²
# This ODE is decoupled from A and C — solver must match the analytical curve.
# Gold generated by: B(t) = 1/(40*exp(0.01*t)-20), t=0.1..400

[Mesh]
  [gen]
    type = GeneratedMeshGenerator
    dim = 1
    nx = 1
  []
[]

[AtmosphericChemistry]
  [Box]
    mechanism_file = '../../../doc/content/modules/atmospheric_chemistry/database/tutorial_5sp.fac'
    mcm_photolysis_file = ''
    temperature = 298
  []
[]

[ICs]
  [A_ic]   type = ScalarConstantIC  variable = A   value = 100  []
  [B_ic]   type = ScalarConstantIC  variable = B   value = 0.05  []
  [C_ic]   type = ScalarConstantIC  variable = C   value = 0  []
  [ONE_ic] type = ScalarConstantIC  variable = ONE value = 1 []
  [RO2_ic] type = ScalarConstantIC  variable = RO2 value = 0 []
[]

[Executioner]
  type = Transient
  solve_type = NEWTON
  scheme = 'bdf2'
  end_time = 400
  dt = 0.1
  nl_rel_tol = 1e-10
  nl_abs_tol = 1e-12
  [TimeStepper]
    type = ConstantDT
    dt = 0.1
  []
[]

[Outputs]
  checkpoint = false
  csv = true
  execute_on = 'timestep_end'
  hide = 'A C RO2'
  file_base = 'vs_F0AM_tutorial5_box'
[]
